/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forme;

import form_poslovni_partner.FormNoviPoslovniPartner;
import form_poslovni_partner.FormPretragaPoslovnogPartnera;
import controller.ClientController;
import domain.Iznajmljivanje;
import domain.PoslovniPartner;
import domain.Stan;
import domain.StavkaIznajmljivanja;
import domain.Zaposleni;
import form_iznajmljivanje.FormPretragaIznajmljivanja;
import form_stan.FormNoviStan;
import form_stan.FormPretragaStan;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import models.TableModelStavkeIznajmljivanja;
import session.Session;

/**
 *
 * @author Ari
 */
public class MainForm extends javax.swing.JFrame {

    private Zaposleni ulogovani;
    private double ukupanIznos;

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
        setLocationRelativeTo(null);
        this.ulogovani = Session.getInstance().getUlogovani();
        lblUlogovani.setText("Ulogovani zaposleni: " + ulogovani);
        setTitle("Klijentska forma");
        txtUkupanIznos.setEditable(false);
        txtBrojDana.setEditable(false);
        txtIznos.setEditable(false);
        popuniPoslovnePartenere();
        popuniStanove();
        tblStavke.setModel(new TableModelStavkeIznajmljivanja());

        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        addWindowListener(new WindowAdapter() {
            public void windowClosing(WindowEvent e) {
                int response = JOptionPane.showConfirmDialog(
                        null,
                        "Da li ste sigurni da zelite da se odjavite?",
                        "Confirm Exit",
                        JOptionPane.YES_NO_OPTION
                );

                if (response == JOptionPane.YES_OPTION) {
                    try {
                        ClientController.getInstance().logout(ulogovani);
                        System.exit(0);
                    } catch (Exception ex) {
                        Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUlogovani = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbStan = new javax.swing.JComboBox();
        txtDatumOd = new javax.swing.JFormattedTextField();
        txtDatumDo = new javax.swing.JFormattedTextField();
        txtBrojDana = new javax.swing.JTextField();
        txtIznos = new javax.swing.JTextField();
        btnDodaj = new javax.swing.JButton();
        btnObrisi = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblStavke = new javax.swing.JTable();
        btnIzracunaj = new javax.swing.JButton();
        btnSacuvaj = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbPoslovniPartner = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtOpis = new javax.swing.JTextArea();
        txtUkupanIznos = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        miPoslovniPartner = new javax.swing.JMenuItem();
        miPretragaPoslovnogPartnera = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        miNoviStan = new javax.swing.JMenuItem();
        miPretragaStana = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        miPretragaIznajmljivanja = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        miOdjava = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblUlogovani.setText("Ulogovani");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Iznajmljivanje"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Stavka iznajmljivanja"));

        jLabel4.setText("Stan:");

        jLabel5.setText("Datum od:");

        jLabel6.setText("Datum do:");

        jLabel7.setText("Broj dana:");

        jLabel8.setText("Iznos:");

        cmbStan.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbStan.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbStanItemStateChanged(evt);
            }
        });

        txtDatumOd.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumOd.setText("11.12.2025");
        txtDatumOd.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumOdKeyReleased(evt);
            }
        });

        txtDatumDo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd.MM.yyyy"))));
        txtDatumDo.setText("15.12.2025");
        txtDatumDo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDatumDoKeyReleased(evt);
            }
        });

        btnDodaj.setText("Dodaj stavku");
        btnDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDodajActionPerformed(evt);
            }
        });

        btnObrisi.setText("Obrisi stavku");
        btnObrisi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnObrisiActionPerformed(evt);
            }
        });

        tblStavke.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblStavke);

        btnIzracunaj.setText("Izracunaj broj dana");
        btnIzracunaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIzracunajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnIzracunaj, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnDodaj, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnObrisi, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cmbStan, 0, 575, Short.MAX_VALUE)
                                    .addComponent(txtDatumOd)
                                    .addComponent(txtDatumDo)
                                    .addComponent(txtBrojDana)
                                    .addComponent(txtIznos))))))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbStan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtDatumOd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDatumDo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnIzracunaj)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBrojDana, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDodaj)
                    .addComponent(btnObrisi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSacuvaj.setText("Sacuvaj iznajmljivanje");
        btnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSacuvajActionPerformed(evt);
            }
        });

        jLabel1.setText("Poslovni partner:");

        jLabel2.setText("Opis:");

        jLabel3.setText("Ukupan iznos:");

        cmbPoslovniPartner.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        txtOpis.setColumns(20);
        txtOpis.setRows(5);
        txtOpis.setText("Neki opis");
        jScrollPane1.setViewportView(txtOpis);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(50, 50, 50)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbPoslovniPartner, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1)
                            .addComponent(txtUkupanIznos))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cmbPoslovniPartner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtUkupanIznos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSacuvaj, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu6.setText("Poslovni partner");

        miPoslovniPartner.setText("Novi poslovni partner");
        miPoslovniPartner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPoslovniPartnerActionPerformed(evt);
            }
        });
        jMenu6.add(miPoslovniPartner);

        miPretragaPoslovnogPartnera.setText("Pretraga poslovnog partnera");
        miPretragaPoslovnogPartnera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaPoslovnogPartneraActionPerformed(evt);
            }
        });
        jMenu6.add(miPretragaPoslovnogPartnera);

        jMenuBar1.add(jMenu6);

        jMenu8.setText("Stan");

        miNoviStan.setText("Novi stan");
        miNoviStan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miNoviStanActionPerformed(evt);
            }
        });
        jMenu8.add(miNoviStan);

        miPretragaStana.setText("Pretraga stana");
        miPretragaStana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaStanaActionPerformed(evt);
            }
        });
        jMenu8.add(miPretragaStana);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Iznajmljivanje");

        miPretragaIznajmljivanja.setText("Pretraga iznajmljivanja");
        miPretragaIznajmljivanja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miPretragaIznajmljivanjaActionPerformed(evt);
            }
        });
        jMenu9.add(miPretragaIznajmljivanja);

        jMenuBar1.add(jMenu9);

        jMenu7.setText("Odjava");

        miOdjava.setText("Odjavi se");
        miOdjava.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miOdjavaActionPerformed(evt);
            }
        });
        jMenu7.add(miOdjava);

        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblUlogovani))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUlogovani)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miPoslovniPartnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPoslovniPartnerActionPerformed
        new FormNoviPoslovniPartner(this, true).setVisible(true);
    }//GEN-LAST:event_miPoslovniPartnerActionPerformed

    private void miPretragaPoslovnogPartneraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaPoslovnogPartneraActionPerformed
        new FormPretragaPoslovnogPartnera(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaPoslovnogPartneraActionPerformed

    private void miOdjavaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miOdjavaActionPerformed
        int result = JOptionPane.showConfirmDialog(this, "Da li ste sigurni da zelite da "
                + "se odjavite?", "Konfirmacija", JOptionPane.YES_NO_OPTION);

        if (result == JOptionPane.NO_OPTION) {
            return;
        }

        if (result == JOptionPane.YES_OPTION) {
            try {
                ClientController.getInstance().logout(ulogovani);
                new LoginForma().setVisible(true);
                Session.getInstance().setUlogovani(null);
                this.dispose();
            } catch (Exception ex) {
                Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_miOdjavaActionPerformed

    private void miNoviStanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miNoviStanActionPerformed
        new FormNoviStan(this, true).setVisible(true);
    }//GEN-LAST:event_miNoviStanActionPerformed

    private void miPretragaStanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaStanaActionPerformed
        new FormPretragaStan(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaStanaActionPerformed

    private void miPretragaIznajmljivanjaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miPretragaIznajmljivanjaActionPerformed
        new FormPretragaIznajmljivanja(this, true).setVisible(true);
    }//GEN-LAST:event_miPretragaIznajmljivanjaActionPerformed

    private void btnIzracunajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIzracunajActionPerformed

        if (txtDatumOd.getText().isEmpty() || txtDatumDo.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate popuniti datum prijave i datum odjave!");
            return;
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumOd = sdf.parse(txtDatumOd.getText());
            Date datumDo = sdf.parse(txtDatumDo.getText());

            if (datumOd.after(datumDo) || datumOd.equals(datumDo)) {
                JOptionPane.showMessageDialog(this, "Datum pocetka mora biti pre datuma kraja!");
                return;
            }

            if (datumOd.before(new Date()) || datumOd.equals(datumDo)) {
                JOptionPane.showMessageDialog(this, "Datum pocetka mora biti u buducnosti!");
                return;
            }

            long diffInMillies = datumDo.getTime() - datumOd.getTime();
            long brojDana = TimeUnit.DAYS.convert(diffInMillies, TimeUnit.MILLISECONDS);

            txtBrojDana.setText(String.valueOf(brojDana));

            Stan stan = (Stan) cmbStan.getSelectedItem();
            txtIznos.setText(String.valueOf(stan.getCenaPoDanu() * brojDana));

        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnIzracunajActionPerformed

    private void cmbStanItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbStanItemStateChanged

        if (cmbStan.getSelectedItem() != null) {
            txtBrojDana.setText("");
            txtIznos.setText("");
        }

    }//GEN-LAST:event_cmbStanItemStateChanged

    private void txtDatumOdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumOdKeyReleased
        txtBrojDana.setText("");
        txtIznos.setText("");
    }//GEN-LAST:event_txtDatumOdKeyReleased

    private void txtDatumDoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDatumDoKeyReleased
        txtBrojDana.setText("");
        txtIznos.setText("");
    }//GEN-LAST:event_txtDatumDoKeyReleased

    private void btnDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDodajActionPerformed

        if (txtBrojDana.getText().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Morate izracunati broj dana!");
            return;
        }

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy");
            Date datumOd = sdf.parse(txtDatumOd.getText());
            Date datumDo = sdf.parse(txtDatumDo.getText());
            int brojDana = Integer.parseInt(txtBrojDana.getText());
            double iznos = Double.parseDouble(txtIznos.getText());
            Stan stan = (Stan) cmbStan.getSelectedItem();

            StavkaIznajmljivanja si = new StavkaIznajmljivanja(null, -1,
                    datumOd, datumDo, brojDana,
                    stan.getCenaPoDanu(), iznos, stan);

            TableModelStavkeIznajmljivanja tm = (TableModelStavkeIznajmljivanja) tblStavke.getModel();
            
            if(tm.postojiStan(stan)){
                JOptionPane.showMessageDialog(this, "Vec ste uneli ovaj stan!");
                return;
            }
            
            tm.dodajStavku(si);

            ukupanIznos = tm.vratiUkupanIznos();
            txtUkupanIznos.setText(String.valueOf(ukupanIznos) + "€");

        } catch (ParseException ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnDodajActionPerformed

    private void btnObrisiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnObrisiActionPerformed

        int row = tblStavke.getSelectedRow();

        if (row >= 0) {
            TableModelStavkeIznajmljivanja tm = (TableModelStavkeIznajmljivanja) tblStavke.getModel();
            tm.obrisiStavku(row);

            ukupanIznos = tm.vratiUkupanIznos();
            txtUkupanIznos.setText(String.valueOf(ukupanIznos) + "€");
        }

    }//GEN-LAST:event_btnObrisiActionPerformed

    private void btnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSacuvajActionPerformed

        try {
            if (txtOpis.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Morate uneti opis!");
                return;
            }

            PoslovniPartner poslovniPartner = (PoslovniPartner) cmbPoslovniPartner.getSelectedItem();
            String opis = txtOpis.getText();

            TableModelStavkeIznajmljivanja tm = (TableModelStavkeIznajmljivanja) tblStavke.getModel();

            Iznajmljivanje i = new Iznajmljivanje(-1, opis, ukupanIznos,
                    poslovniPartner, ulogovani, tm.getLista());

            ClientController.getInstance().addIznajmljivanje(i);
            txtBrojDana.setText("");
            txtIznos.setText("");
            txtOpis.setText("");
            txtUkupanIznos.setText("");
            ukupanIznos = 0;
            tm.getLista().clear();
            tm.fireTableDataChanged();
            JOptionPane.showMessageDialog(this, "Uspesno sacuvano iznajmljivanje!");

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
//            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btnSacuvajActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDodaj;
    private javax.swing.JButton btnIzracunaj;
    private javax.swing.JButton btnObrisi;
    private javax.swing.JButton btnSacuvaj;
    private javax.swing.JComboBox cmbPoslovniPartner;
    private javax.swing.JComboBox cmbStan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblUlogovani;
    private javax.swing.JMenuItem miNoviStan;
    private javax.swing.JMenuItem miOdjava;
    private javax.swing.JMenuItem miPoslovniPartner;
    private javax.swing.JMenuItem miPretragaIznajmljivanja;
    private javax.swing.JMenuItem miPretragaPoslovnogPartnera;
    private javax.swing.JMenuItem miPretragaStana;
    private javax.swing.JTable tblStavke;
    private javax.swing.JTextField txtBrojDana;
    private javax.swing.JFormattedTextField txtDatumDo;
    private javax.swing.JFormattedTextField txtDatumOd;
    private javax.swing.JTextField txtIznos;
    private javax.swing.JTextArea txtOpis;
    private javax.swing.JTextField txtUkupanIznos;
    // End of variables declaration//GEN-END:variables

    private void popuniPoslovnePartenere() {
        try {
            ArrayList<PoslovniPartner> poslovniPartneri = ClientController.getInstance().getAllPoslovniPartner();

            cmbPoslovniPartner.removeAllItems();

            for (PoslovniPartner poslovniPartner : poslovniPartneri) {
                cmbPoslovniPartner.addItem(poslovniPartner);
            }
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void popuniStanove() {
        try {
            ArrayList<Stan> stanovi = ClientController.getInstance().getAllStan();

            cmbStan.removeAllItems();

            for (Stan stan : stanovi) {
                cmbStan.addItem(stan);
            }
        } catch (Exception ex) {
            Logger.getLogger(MainForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

}
